Running with gitlab-runner 17.10.0~pre.41.g5c23fd8e (5c23fd8e)
  on blue-6.saas-linux-small-amd64.runners-manager.gitlab.com/default nN8vMRS9Z, system ID: s_a899fcd611a3
Preparing the "docker+machine" executor
00:30
Using Docker executor with image docker:20.10-dind ...
Starting service docker:20.10-dind...
Pulling docker image docker:20.10-dind ...
Using docker image sha256:c0e053541b0eec2ee002f3862daedf169d40ff5e65d2a11206ebb1dd883acc13 for docker:20.10-dind with digest docker@sha256:af96c680a7e1f853ebdd50c1e0577e5df4089b033102546dd6417419564df3b5 ...
Waiting for services to be up and running (timeout 30 seconds)...
Using docker image sha256:c0e053541b0eec2ee002f3862daedf169d40ff5e65d2a11206ebb1dd883acc13 for docker:20.10-dind with digest docker@sha256:af96c680a7e1f853ebdd50c1e0577e5df4089b033102546dd6417419564df3b5 ...
Preparing environment
00:01
Running on runner-nn8vmrs9z-project-68482359-concurrent-0 via runner-nn8vmrs9z-s-l-s-amd64-1743228189-8796bd41...
Getting source from Git repository
00:03
Fetching changes with git depth set to 1...
Initialized empty Git repository in /builds/qlkwej-org/test-ci-cd-juice-shop/.git/
Created fresh repository.
Checking out 96f770ac as detached HEAD (ref is master)...
Skipping Git submodules setup
$ git remote set-url origin "${CI_REPOSITORY_URL}" || echo 'Not a git repository; skipping'
Executing "step_script" stage of the job script
11:54
Using docker image sha256:c0e053541b0eec2ee002f3862daedf169d40ff5e65d2a11206ebb1dd883acc13 for docker:20.10-dind with digest docker@sha256:af96c680a7e1f853ebdd50c1e0577e5df4089b033102546dd6417419564df3b5 ...
$ docker build  --build-arg NODE_OPTIONS="--max-old-space-size=4096" --progress=plain -t juice-shop:$CI_COMMIT_SHA .
#1 [internal] load build definition from Dockerfile
#1 sha256:8ef8b025b07abe56101c734b52a9d2a9563d15115414593e0595b8143f9f1f9e
#1 transferring dockerfile: 2.26kB done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 sha256:abf18703c8e5bd36c0e3531bb98df6965e4581592c434cdb6298eac48f3452c8
#2 transferring context: 285B done
#2 DONE 0.0s
#4 [internal] load metadata for docker.io/library/node:20-buster
#4 sha256:de63487591a7dfa03f44f4db0f6ce993177f4aedaf8e46b18cd29e1fa1ca1989
#4 DONE 0.5s
#3 [internal] load metadata for gcr.io/distroless/nodejs20-debian11:latest
#3 sha256:7083bea0ccd360c40024c182be272d9e80895e5581ed4bf5db7deecc8e8229e9
#3 DONE 0.7s
#7 [libxmljs-builder 1/5] FROM docker.io/library/node:20-buster@sha256:479103df06b40b90f189461b6f824a62906683e26a32c77d7c3e2d855a0e3e9f
#7 sha256:b7effa805a4b3cfd18388627e07d788b70897b8ae4875d7e5a5d2bea35978a56
#7 resolve docker.io/library/node:20-buster@sha256:479103df06b40b90f189461b6f824a62906683e26a32c77d7c3e2d855a0e3e9f 0.0s done
#7 sha256:e789c1e41c485bf1ebec54eee06e33c1480fbfb4cfa6c354489e248d35c12fbf 6.59kB / 6.59kB done
#7 sha256:210343259138ad1b7bad23cd3be6aa1126f764f887c639749411387c9321c2d5 2.50kB / 2.50kB done
#7 sha256:479103df06b40b90f189461b6f824a62906683e26a32c77d7c3e2d855a0e3e9f 2.62kB / 2.62kB done
#7 ...
#8 [internal] load build context
#8 sha256:c56405403d640715b58af59463d72ca0c4b7effc75c70a0c41995d7dd8b31376
#8 transferring context: 47.10MB 0.9s done
#8 DONE 0.9s
#5 [stage-2 1/4] FROM gcr.io/distroless/nodejs20-debian11@sha256:a3c4d477f3f303cfdf2b43b0a255fb5a0d435957b466819b3c0940d9d05404b6
#5 sha256:84533addd96a1d101f01569c84a6d3d05641fbfa98b88763adbaf2998a020c63
#5 resolve gcr.io/distroless/nodejs20-debian11@sha256:a3c4d477f3f303cfdf2b43b0a255fb5a0d435957b466819b3c0940d9d05404b6 0.0s done
#5 sha256:4f2cf66225b06522d3b47266c2234ed47aa8ebd4bd3eef5e717c727fcb835d70 3.05kB / 3.05kB done
#5 sha256:a3c4d477f3f303cfdf2b43b0a255fb5a0d435957b466819b3c0940d9d05404b6 1.51kB / 1.51kB done
#5 sha256:661ffa98acab88b2addd7a6426d0f7cd47906a1a45cd27cb27c411cb76b160af 2.28kB / 2.28kB done
#5 sha256:e33bce57de289fffd2380f73997dfb7e1ec193877904bed99f28c715d071fdc4 21.19kB / 21.19kB 0.2s done
#5 sha256:1c56d6035a42c0a75d79cc88acf6c9d4104343639f19b8262b520c449731445d 104.12kB / 104.12kB 0.2s done
#5 sha256:473d8557b1b27974f7dc7c4b4e1a209df0e27e8cae1e3e33b7bb45c969b6fc7e 755.28kB / 755.28kB 0.2s done
#5 extracting sha256:1c56d6035a42c0a75d79cc88acf6c9d4104343639f19b8262b520c449731445d done
#5 sha256:b6824ed73363f94b3b2b44084c51c31bc32af77a96861d49e16f91e3ab6bed71 67B / 67B 0.4s done
#5 sha256:7c12895b777bcaa8ccae0605b4de635b68fc32d60fa08f421dc3818bf55ee212 188B / 188B 0.4s done
#5 sha256:33e068de264953dfdc9f9ada207e76b61159721fd64a4820b320d05133a55fb8 122B / 122B 0.4s done
#5 extracting sha256:e33bce57de289fffd2380f73997dfb7e1ec193877904bed99f28c715d071fdc4 done
#5 extracting sha256:473d8557b1b27974f7dc7c4b4e1a209df0e27e8cae1e3e33b7bb45c969b6fc7e 0.5s done
#5 sha256:5664b15f108bf9436ce3312090a767300800edbbfd4511aa1a6d64357024d5dd 168B / 168B 0.6s done
#5 sha256:27be814a09ebd97fac6fb7b82d19f117185e90601009df3fbab6f442f85cd6b3 93B / 93B 0.6s done
#5 sha256:4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f 385B / 385B 0.6s done
#5 sha256:9112d77ee5b16873acaa186b816c3c61f5f8eba40730e729e9614a27f40211e0 122.56kB / 122.56kB 0.7s done
#5 sha256:83f8d4690e1f293d0438aef7d1075e590ce77fdec97bb4d90b1d227aeba343fd 5.85MB / 5.85MB 0.8s done
#5 sha256:9ef7d74bdfdf3c517b28bd694a9159e94e5f53ff1ca87b39f8ca1ac0be2ed317 320B / 320B 0.8s done
#5 sha256:a4ba90834fb4abf3d80bbdaaaef36560ab1bb682f5279d44114d768e119639b9 2.06MB / 2.06MB 1.0s
#5 sha256:df368711b36276ed02b2040d3e3296b919042d2a05a2bbe9f758e708436c12cf 968.57kB / 968.57kB 1.0s done
#5 sha256:e89169bec965f3b73bc8a6cf650d362a1da8ae571c5fdccccf7bab8194c03c47 0B / 131.15kB 1.0s
#5 extracting sha256:b6824ed73363f94b3b2b44084c51c31bc32af77a96861d49e16f91e3ab6bed71 done
#5 extracting sha256:7c12895b777bcaa8ccae0605b4de635b68fc32d60fa08f421dc3818bf55ee212
#5 sha256:a4ba90834fb4abf3d80bbdaaaef36560ab1bb682f5279d44114d768e119639b9 2.06MB / 2.06MB 1.0s done
#5 sha256:e89169bec965f3b73bc8a6cf650d362a1da8ae571c5fdccccf7bab8194c03c47 131.15kB / 131.15kB 1.0s done
#5 extracting sha256:7c12895b777bcaa8ccae0605b4de635b68fc32d60fa08f421dc3818bf55ee212 done
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 0B / 41.48MB 1.1s
#5 sha256:7f3501c931c2f262add9c59a46b7469c09f862cfcdb005d9187bc4f8f9964724 0B / 741.33kB 1.1s
#5 sha256:88934a1bc18c35762f0009512e7a775aec9e1d9531a1781a0caf81013a67ab94 0B / 52.41kB 1.1s
#5 extracting sha256:33e068de264953dfdc9f9ada207e76b61159721fd64a4820b320d05133a55fb8 done
#5 sha256:7f3501c931c2f262add9c59a46b7469c09f862cfcdb005d9187bc4f8f9964724 741.33kB / 741.33kB 1.1s done
#5 extracting sha256:5664b15f108bf9436ce3312090a767300800edbbfd4511aa1a6d64357024d5dd done
#5 extracting sha256:27be814a09ebd97fac6fb7b82d19f117185e90601009df3fbab6f442f85cd6b3 done
#5 extracting sha256:4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f
#5 sha256:88934a1bc18c35762f0009512e7a775aec9e1d9531a1781a0caf81013a67ab94 52.41kB / 52.41kB 1.2s done
#5 extracting sha256:4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f done
#5 extracting sha256:9ef7d74bdfdf3c517b28bd694a9159e94e5f53ff1ca87b39f8ca1ac0be2ed317 done
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 9.33MB / 41.48MB 1.5s
#5 extracting sha256:9112d77ee5b16873acaa186b816c3c61f5f8eba40730e729e9614a27f40211e0 done
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 18.87MB / 41.48MB 1.6s
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 26.21MB / 41.48MB 1.7s
#5 extracting sha256:83f8d4690e1f293d0438aef7d1075e590ce77fdec97bb4d90b1d227aeba343fd
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 35.65MB / 41.48MB 1.8s
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 41.48MB / 41.48MB 1.9s
#5 sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 41.48MB / 41.48MB 2.0s done
#5 extracting sha256:83f8d4690e1f293d0438aef7d1075e590ce77fdec97bb4d90b1d227aeba343fd 0.5s done
#5 extracting sha256:a4ba90834fb4abf3d80bbdaaaef36560ab1bb682f5279d44114d768e119639b9
#5 extracting sha256:a4ba90834fb4abf3d80bbdaaaef36560ab1bb682f5279d44114d768e119639b9 0.3s done
#5 extracting sha256:df368711b36276ed02b2040d3e3296b919042d2a05a2bbe9f758e708436c12cf
#5 extracting sha256:df368711b36276ed02b2040d3e3296b919042d2a05a2bbe9f758e708436c12cf 0.1s done
#5 extracting sha256:e89169bec965f3b73bc8a6cf650d362a1da8ae571c5fdccccf7bab8194c03c47 done
#5 extracting sha256:7f3501c931c2f262add9c59a46b7469c09f862cfcdb005d9187bc4f8f9964724
#5 extracting sha256:7f3501c931c2f262add9c59a46b7469c09f862cfcdb005d9187bc4f8f9964724 0.1s done
#5 extracting sha256:88934a1bc18c35762f0009512e7a775aec9e1d9531a1781a0caf81013a67ab94
#5 extracting sha256:88934a1bc18c35762f0009512e7a775aec9e1d9531a1781a0caf81013a67ab94 done
#5 extracting sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6
#5 extracting sha256:e5035db4cc0ad10587dbf34eb63fff1d8d460b92079b04bc8a1e9d228f306fb6 1.6s done
#5 DONE 6.3s
#7 [libxmljs-builder 1/5] FROM docker.io/library/node:20-buster@sha256:479103df06b40b90f189461b6f824a62906683e26a32c77d7c3e2d855a0e3e9f
#7 sha256:b7effa805a4b3cfd18388627e07d788b70897b8ae4875d7e5a5d2bea35978a56
#7 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 50.66MB / 50.66MB 2.4s done
#7 sha256:32ab8bed435ee0e35413bb45d14dae2283dc0841644d881be35089debdc88cc3 17.59MB / 17.59MB 1.6s done
#7 sha256:2a567eb2264b60aa779a5bc8f8f4dc7a6d3e1e01d8f5d1bcd039ed444d91a408 51.90MB / 51.90MB 2.8s done
#7 sha256:9be81a73cfb7b45f4634965206adaa318a889f15cff6ced0ffd70f7c2d851fe4 191.96MB / 191.96MB 5.8s done
#7 extracting sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 3.5s done
#7 sha256:3bcf1cf7cb91fe6b1ebeb2a4113148f94e21b4e399fba8fc08cdee7a0c5104a1 48.02MB / 48.02MB 3.8s done
#7 sha256:a508c11d72bec9ab7ecb8e2f18f9399603b028f6eb8da53a4411c5f9a15dd921 4.09kB / 4.09kB 3.0s done
#7 sha256:e20b342eff9190e35ab3c6a9e05cac912ebed6848d3fa4caaa1dc31f28acd6f9 1.25MB / 1.25MB 3.2s done
#7 sha256:ab80d1950cdb44d12f0729d9d9d3f624dd1d347ca142b323742a79ce2e32d8f1 452B / 452B 3.3s done
#7 extracting sha256:32ab8bed435ee0e35413bb45d14dae2283dc0841644d881be35089debdc88cc3
#7 extracting sha256:32ab8bed435ee0e35413bb45d14dae2283dc0841644d881be35089debdc88cc3 0.7s done
#7 ...
#6 [stage-2 2/4] WORKDIR /juice-shop
#6 sha256:debab7b4762528e8c882ec8b0996a6252d8cee5673fa3d5f61555a55a7bc814b
#6 DONE 2.9s
#7 [libxmljs-builder 1/5] FROM docker.io/library/node:20-buster@sha256:479103df06b40b90f189461b6f824a62906683e26a32c77d7c3e2d855a0e3e9f
#7 sha256:b7effa805a4b3cfd18388627e07d788b70897b8ae4875d7e5a5d2bea35978a56
#7 extracting sha256:2a567eb2264b60aa779a5bc8f8f4dc7a6d3e1e01d8f5d1bcd039ed444d91a408 0.1s
#7 extracting sha256:2a567eb2264b60aa779a5bc8f8f4dc7a6d3e1e01d8f5d1bcd039ed444d91a408 1.9s done
#7 extracting sha256:9be81a73cfb7b45f4634965206adaa318a889f15cff6ced0ffd70f7c2d851fe4
#7 extracting sha256:9be81a73cfb7b45f4634965206adaa318a889f15cff6ced0ffd70f7c2d851fe4 5.0s
#7 extracting sha256:9be81a73cfb7b45f4634965206adaa318a889f15cff6ced0ffd70f7c2d851fe4 5.9s done
#7 extracting sha256:a508c11d72bec9ab7ecb8e2f18f9399603b028f6eb8da53a4411c5f9a15dd921 done
#7 extracting sha256:3bcf1cf7cb91fe6b1ebeb2a4113148f94e21b4e399fba8fc08cdee7a0c5104a1 0.1s
#7 extracting sha256:3bcf1cf7cb91fe6b1ebeb2a4113148f94e21b4e399fba8fc08cdee7a0c5104a1 1.9s done
#7 extracting sha256:e20b342eff9190e35ab3c6a9e05cac912ebed6848d3fa4caaa1dc31f28acd6f9 0.1s done
#7 extracting sha256:ab80d1950cdb44d12f0729d9d9d3f624dd1d347ca142b323742a79ce2e32d8f1
#7 extracting sha256:ab80d1950cdb44d12f0729d9d9d3f624dd1d347ca142b323742a79ce2e32d8f1 done
#7 DONE 19.9s
#27 [libxmljs-builder 2/5] WORKDIR /juice-shop
#27 sha256:fc77d94f901297d943a7ce7c6f3c2ba9535fe12d3a5b159393a76bf5514dc6d2
#27 DONE 6.6s
#9 [installer  2/18] COPY . /juice-shop
#9 sha256:a56d9bae073f83401709f9d5146a24fbebcf092a1ec299ab9c4017f62a661f6c
#9 DONE 6.7s
#10 [installer  3/18] WORKDIR /juice-shop
#10 sha256:5fb640151bf4c397d11c592fccdb2f5909e50f58355b6ba684cc9ba82064aa06
#10 DONE 0.2s
#28 [libxmljs-builder 3/5] RUN apt-get update && apt-get install -y build-essential python3
#28 sha256:368a110d093654b0a3abcd7d5b7e9017d5427b5a3ad6139dfbe7176c4cfb0d3a
#28 0.449 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
#28 0.510 Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
#28 0.525 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
#28 0.682 Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
#28 0.969 Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [610 kB]
#28 1.268 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
#28 2.503 Fetched 8741 kB in 2s (4204 kB/s)
#28 2.503 Reading package lists...
#28 3.184 Reading package lists...
#28 4.026 Building dependency tree...
#28 4.231 Reading state information...
#28 4.379 python3 is already the newest version (3.7.3-1).
#28 4.379 python3 set to manually installed.
#28 4.379 The following NEW packages will be installed:
#28 4.380   build-essential
#28 4.437 0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
#28 4.437 Need to get 7576 B of archives.
#28 4.437 After this operation, 20.5 kB of additional disk space will be used.
#28 4.437 Get:1 http://deb.debian.org/debian buster/main amd64 build-essential amd64 12.6 [7576 B]
#28 4.898 debconf: delaying package configuration, since apt-utils is not installed
#28 ...
#11 [installer  4/18] RUN npm i -g typescript ts-node
#11 sha256:b0cf2e58f47dfe067601c3e25c189bad2cdfaa782ada2e025f3822d408266181
#11 4.296 
#11 4.296 added 20 packages in 4s
#11 4.297 npm notice
#11 4.297 npm notice New major version of npm available! 10.7.0 -> 11.2.0
#11 4.297 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.2.0
#11 4.297 npm notice To update run: npm install -g npm@11.2.0
#11 4.297 npm notice
#11 DONE 4.9s
#28 [libxmljs-builder 3/5] RUN apt-get update && apt-get install -y build-essential python3
#28 sha256:368a110d093654b0a3abcd7d5b7e9017d5427b5a3ad6139dfbe7176c4cfb0d3a
#28 5.110 Fetched 7576 B in 0s (170 kB/s)
#28 5.151 Selecting previously unselected package build-essential.
#28 5.151 (Reading database ... 
#28 ...
#12 [installer  5/18] RUN npm install --omit=dev --unsafe-perm
#12 sha256:f18249e6bb063b815e7d3726f7931a4e7c7d0c87a9127cf00ec4bbca5ae52aca
#12 ...
#28 [libxmljs-builder 3/5] RUN apt-get update && apt-get install -y build-essential python3
#28 sha256:368a110d093654b0a3abcd7d5b7e9017d5427b5a3ad6139dfbe7176c4cfb0d3a
(Reading database ... 23957 files and directories currently installed.)
#28 5.170 Preparing to unpack .../build-essential_12.6_amd64.deb ...
#28 5.174 Unpacking build-essential (12.6) ...
#28 5.224 Setting up build-essential (12.6) ...
#28 DONE 5.3s
#12 [installer  5/18] RUN npm install --omit=dev --unsafe-perm
#12 sha256:f18249e6bb063b815e7d3726f7931a4e7c7d0c87a9127cf00ec4bbca5ae52aca
#12 82.65 npm warn deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
#12 82.97 npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
#12 83.06 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#12 83.19 npm warn deprecated eivindfjeldstad-dot@0.0.1: Use @eivifj/dot instead
#12 83.25 npm warn deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
#12 83.94 npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#12 83.99 npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#12 83.99 npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
#12 84.21 npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
#12 84.31 npm warn deprecated har-validator@5.1.5: this library is no longer supported
#12 84.84 npm warn deprecated fstream@1.0.12: This package is no longer supported.
#12 84.92 npm warn deprecated are-we-there-yet@1.1.7: This package is no longer supported.
#12 86.18 npm warn deprecated gauge@2.7.4: This package is no longer supported.
#12 86.38 npm warn deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.
#12 86.47 npm warn deprecated npmlog@4.1.2: This package is no longer supported.
#12 86.79 npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#12 87.36 npm warn deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat@4' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
#12 87.47 npm warn deprecated vm2@3.9.17: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
#12 88.17 npm warn deprecated osenv@0.1.5: This package is no longer supported.
#12 88.52 npm warn deprecated jsonwebtoken@0.4.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
#12 88.57 npm warn deprecated notevil@1.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#12 88.70 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 88.70 npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
#12 89.12 npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#12 89.22 npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
#12 89.22 npm warn deprecated npmlog@5.0.1: This package is no longer supported.
#12 89.38 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 89.40 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 89.43 npm warn deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
#12 89.50 npm warn deprecated gauge@3.0.2: This package is no longer supported.
#12 89.51 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 89.91 npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
#12 89.91 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 90.17 npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
#12 90.66 npm warn deprecated npmlog@6.0.2: This package is no longer supported.
#12 90.66 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 90.80 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 90.83 npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
#12 90.85 npm warn deprecated gauge@4.0.4: This package is no longer supported.
#12 90.89 npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
#12 90.89 npm warn deprecated jsonwebtoken@0.1.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
#12 90.94 npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#12 91.76 npm warn deprecated sinon@1.17.7: 16.1.1
#12 92.14 npm warn deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
#12 125.0 
#12 125.0 > juice-shop@17.2.0 postinstall
#12 125.0 > cd frontend && npm install --legacy-peer-deps && cd .. && npm run build:frontend && (npm run --silent build:server || cd .)
#12 125.0 
#12 215.4 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#12 215.6 npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#12 215.7 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#12 217.0 npm warn deprecated read-package-json@7.0.1: This package is no longer supported. Please use @npmcli/package-json instead.
#12 225.1 npm warn deprecated @angular/flex-layout@15.0.0-beta.42: This package has been deprecated. Please see https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127
#12 231.1 
#12 231.1 added 1020 packages, and audited 1236 packages in 2m
#12 231.1 
#12 231.1 173 packages are looking for funding
#12 231.1   run `npm fund` for details
#12 231.2 
#12 231.2 13 vulnerabilities (7 moderate, 3 high, 3 critical)
#12 231.2 
#12 231.2 To address all issues (including breaking changes), run:
#12 231.2   npm audit fix --force
#12 231.2 
#12 231.2 Run `npm audit` for details.
#12 231.6 
#12 231.6 > juice-shop@17.2.0 build:frontend
#12 231.6 > cd frontend && npm run build
#12 231.6 
#12 231.8 
#12 231.8 > frontend@17.2.0 build
#12 231.8 > ng build --configuration production
#12 231.8 
#12 233.4 - Generating browser application bundles (phase: setup)...
#12 331.3 ✔ Browser application bundle generation complete.
#12 334.7 ✔ Browser application bundle generation complete.
#12 334.7 - Copying assets...
#12 334.8 ✔ Copying assets complete.
#12 334.9 - Generating index html...
#12 335.1 ✔ Index html generation complete.
#12 335.1 
#12 335.1 Initial chunk files | Names                                 |  Raw size | Estimated transfer size
#12 335.1 vendor.js           | vendor                                |   1.58 MB |               330.47 kB
#12 335.1 styles.css          | styles                                | 565.57 kB |                22.73 kB
#12 335.1 main.js             | main                                  | 448.33 kB |                75.49 kB
#12 335.1 polyfills.js        | polyfills                             |  54.19 kB |                17.42 kB
#12 335.1 runtime.js          | runtime                               |   3.24 kB |                 1.49 kB
#12 335.1 
#12 335.1                     | Initial total                         |   2.62 MB |               447.60 kB
#12 335.1 
#12 335.1 Lazy chunk files    | Names                                 |  Raw size | Estimated transfer size
#12 335.1 989.js              | faucet-faucet-module                  | 452.08 kB |               126.09 kB
#12 335.1 380.js              | web3-sandbox-web3-sandbox-module      | 416.96 kB |                95.99 kB
#12 335.1 tutorial.js         | tutorial                              |  35.35 kB |                 8.77 kB
#12 335.1 300.js              | highlight-js-lib-core                 |  20.24 kB |                 7.36 kB
#12 335.1 388.js              | faucet-faucet-module                  |  11.57 kB |                 3.57 kB
#12 335.1 705.js              | confetti                              |  10.86 kB |                 3.93 kB
#12 335.1 common.js           | common                                |   9.04 kB |               856 bytes
#12 335.1 108.js              | highlight-js-lib-languages-typescript |   7.59 kB |                 2.71 kB
#12 335.1 675.js              | wallet-web3-wallet-web3-module        |   6.87 kB |                 2.48 kB
#12 335.1 236.js              | highlight-js-lib-languages-javascript |   6.37 kB |                 2.31 kB
#12 335.1 806.js              | highlightjs-line-numbers-js           |   3.41 kB |                 1.37 kB
#12 335.1 928.js              | highlight-js-lib-languages-yaml       |   1.88 kB |               772 bytes
#12 335.1 
#12 335.1 Build at: 2025-03-29T06:11:40.235Z - Hash: 51df137ce67dcca5 - Time: 101071ms
#12 335.1 
#12 335.1 Warning: /juice-shop/frontend/node_modules/ng-qrcode/fesm2022/ng-qrcode.mjs depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
#12 335.1 For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
#12 335.1 
#12 335.1 
#12 345.9 cypress.config.ts(1,30): error TS2307: Cannot find module 'cypress' or its corresponding type declarations.
#12 345.9 cypress.config.ts(3,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 cypress.config.ts(32,14): error TS7006: Parameter 'product' implicitly has an 'any' type.
#12 345.9 cypress.config.ts(59,14): error TS7006: Parameter 'product' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(26,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 data/datacreator.ts(236,56): error TS7006: Parameter 'product' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(236,65): error TS7006: Parameter 'index' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(257,75): error TS7006: Parameter 'memory' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(296,82): error TS7006: Parameter 'product' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(312,54): error TS7031: Binding element 'useForChristmasSpecialChallenge' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(313,57): error TS7031: Binding element 'keywordsForPastebinDataLeakChallenge' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(314,54): error TS7031: Binding element 'urlForProductTamperingChallenge' implicitly has an 'any' type.
#12 345.9 data/datacreator.ts(315,63): error TS7031: Binding element 'fileForRetrieveBlueprintChallenge' implicitly has an 'any' type.
#12 345.9 data/staticData.ts(3,26): error TS7016: Could not find a declaration file for module 'js-yaml'. '/juice-shop/node_modules/js-yaml/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/js-yaml` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-yaml';`
#12 345.9 data/staticData.ts(55,10): error TS2352: Conversion of type 'string | Logger' to type 'StaticUser[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
#12 345.9   Type 'Logger' is missing the following properties from type 'StaticUser[]': length, pop, concat, join, and 27 more.
#12 345.9 data/staticData.ts(74,10): error TS2352: Conversion of type 'string | Logger' to type 'StaticChallenge[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
#12 345.9   Type 'Logger' is missing the following properties from type 'StaticChallenge[]': length, pop, concat, join, and 27 more.
#12 345.9 data/staticData.ts(85,10): error TS2352: Conversion of type 'string | Logger' to type 'StaticDelivery[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
#12 345.9   Type 'Logger' is missing the following properties from type 'StaticDelivery[]': length, pop, concat, join, and 27 more.
#12 345.9 data/staticData.ts(92,10): error TS2352: Conversion of type 'string | Logger' to type 'StaticSecurityQuestions[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
#12 345.9   Type 'Logger' is missing the following properties from type 'StaticSecurityQuestions[]': length, pop, concat, join, and 27 more.
#12 345.9 lib/antiCheat.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/antiCheat.ts(13,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 lib/challengeUtils.ts(4,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/challengeUtils.ts(5,26): error TS7016: Could not find a declaration file for module 'sanitize-html'. '/juice-shop/node_modules/sanitize-html/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/sanitize-html` if it exists or add a new declaration (.d.ts) file containing `declare module 'sanitize-html';`
#12 345.9 lib/challengeUtils.ts(18,7): error TS2304: Cannot find name 'SocketIOClientStatic'.
#12 345.9 lib/insecurity.ts(8,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 lib/insecurity.ts(10,24): error TS7016: Could not find a declaration file for module 'express-jwt'. '/juice-shop/node_modules/express-jwt/lib/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express-jwt` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-jwt';`
#12 345.9 lib/insecurity.ts(11,17): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/juice-shop/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
#12 345.9 lib/insecurity.ts(12,17): error TS7016: Could not find a declaration file for module 'jws'. '/juice-shop/node_modules/jws/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jws` if it exists or add a new declaration (.d.ts) file containing `declare module 'jws';`
#12 345.9 lib/insecurity.ts(13,29): error TS7016: Could not find a declaration file for module 'sanitize-html'. '/juice-shop/node_modules/sanitize-html/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/sanitize-html` if it exists or add a new declaration (.d.ts) file containing `declare module 'sanitize-html';`
#12 345.9 lib/startup/cleanupFtpFolder.ts(8,16): error TS7016: Could not find a declaration file for module 'fs-extra'. '/juice-shop/node_modules/fs-extra/lib/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/fs-extra` if it exists or add a new declaration (.d.ts) file containing `declare module 'fs-extra';`
#12 345.9 lib/startup/customizeApplication.ts(7,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/customizeEasterEgg.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/registerWebsocketEvents.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/registerWebsocketEvents.ts(16,7): error TS2304: Cannot find name 'SocketIOClientStatic'.
#12 345.9 lib/startup/registerWebsocketEvents.ts(21,3): error TS2578: Unused '@ts-expect-error' directive.
#12 345.9 lib/startup/validateChatBot.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/validateConfig.ts(9,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/validateConfig.ts(33,50): error TS2345: Argument of type 'Product[] | undefined' is not assignable to parameter of type 'Product[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Product[]'.
#12 345.9 lib/startup/validateConfig.ts(34,54): error TS2345: Argument of type 'Product[] | undefined' is not assignable to parameter of type 'Product[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Product[]'.
#12 345.9 lib/startup/validateConfig.ts(35,42): error TS2345: Argument of type 'Product[] | undefined' is not assignable to parameter of type 'Product[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Product[]'.
#12 345.9 lib/startup/validateConfig.ts(36,54): error TS2345: Argument of type 'Product[] | undefined' is not assignable to parameter of type 'Product[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Product[]'.
#12 345.9 lib/startup/validateConfig.ts(37,50): error TS2345: Argument of type 'Memory[] | undefined' is not assignable to parameter of type 'Memory[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Memory[]'.
#12 345.9 lib/startup/validateConfig.ts(38,54): error TS2345: Argument of type 'Memory[] | undefined' is not assignable to parameter of type 'Memory[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Memory[]'.
#12 345.9 lib/startup/validateConfig.ts(39,42): error TS2345: Argument of type 'Memory[] | undefined' is not assignable to parameter of type 'Memory[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Memory[]'.
#12 345.9 lib/startup/validateConfig.ts(40,54): error TS2345: Argument of type 'Memory[] | undefined' is not assignable to parameter of type 'Memory[]'.
#12 345.9   Type 'undefined' is not assignable to type 'Memory[]'.
#12 345.9 lib/startup/validatePreconditions.ts(7,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/startup/validatePreconditions.ts(13,20): error TS7016: Could not find a declaration file for module 'semver'. '/juice-shop/node_modules/semver/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`
#12 345.9 lib/startup/validatePreconditions.ts(14,25): error TS7016: Could not find a declaration file for module 'portscanner'. '/juice-shop/node_modules/portscanner/lib/portscanner.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/portscanner` if it exists or add a new declaration (.d.ts) file containing `declare module 'portscanner';`
#12 345.9 lib/utils.ts(10,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/utils.ts(12,22): error TS7016: Could not find a declaration file for module 'download'. '/juice-shop/node_modules/download/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/download` if it exists or add a new declaration (.d.ts) file containing `declare module 'download';`
#12 345.9 lib/utils.ts(14,22): error TS7016: Could not find a declaration file for module 'clarinet'. '/juice-shop/node_modules/clarinet/clarinet.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/clarinet` if it exists or add a new declaration (.d.ts) file containing `declare module 'clarinet';`
#12 345.9 lib/webhook.ts(8,21): error TS7016: Could not find a declaration file for module 'request'. '/juice-shop/node_modules/request/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`
#12 345.9 lib/webhook.ts(10,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 lib/webhook.ts(12,60): error TS7016: Could not find a declaration file for module 'request'. '/juice-shop/node_modules/request/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`
#12 345.9 lib/webhook.ts(22,35): error TS2554: Expected 1 arguments, but got 2.
#12 345.9 lib/webhook.ts(40,109): error TS18046: 'res' is of type 'unknown'.
#12 345.9 lib/webhook.ts(40,145): error TS18046: 'res' is of type 'unknown'.
#12 345.9 lib/webhook.ts(40,185): error TS18046: 'res' is of type 'unknown'.
#12 345.9 models/user.ts(7,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/2fa.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/2fa.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/address.ts(6,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/angular.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/appConfiguration.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/appConfiguration.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/appVersion.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/appVersion.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/authenticatedUsers.ts(5,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/authenticatedUsers.ts(7,24): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/juice-shop/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
#12 345.9 routes/b2bOrder.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/basket.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/basketItems.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/captcha.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/changePassword.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/chatbot.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/chatbot.ts(10,57): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/juice-shop/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
#12 345.9 routes/chatbot.ts(13,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/chatbot.ts(14,22): error TS7016: Could not find a declaration file for module 'download'. '/juice-shop/node_modules/download/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/download` if it exists or add a new declaration (.d.ts) file containing `declare module 'download';`
#12 345.9 routes/chatbot.ts(16,26): error TS7016: Could not find a declaration file for module 'lodash'. '/juice-shop/node_modules/lodash/lodash.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`
#12 345.9 routes/checkKeys.ts(1,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/continueCode.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/countryMapping.ts(6,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/coupon.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/createProductReviews.ts(6,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/currentUser.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/dataErasure.ts(5,73): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/dataErasure.ts(74,13): error TS7006: Parameter 'error' implicitly has an 'any' type.
#12 345.9 routes/dataErasure.ts(74,20): error TS7006: Parameter 'html' implicitly has an 'any' type.
#12 345.9 routes/dataExport.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/delivery.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/deluxe.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/easterEgg.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/fileServer.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/fileUpload.ts(9,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/imageCaptcha.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/keyServer.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/languages.ts(8,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/likeProductReviews.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/logfileServer.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/login.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/login.ts(12,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/memory.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/metrics.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/metrics.ts(16,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/metrics.ts(23,24): error TS7016: Could not find a declaration file for module 'on-finished'. '/juice-shop/node_modules/on-finished/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/on-finished` if it exists or add a new declaration (.d.ts) file containing `declare module 'on-finished';`
#12 345.9 routes/nftMint.ts(1,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/order.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/order.ts(15,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/orderHistory.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/payment.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/premiumReward.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/privacyPolicyProof.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/profileImageFileUpload.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/profileImageFileUpload.ts(30,13): error TS2578: Unused '@ts-expect-error' directive.
#12 345.9 routes/profileImageUrlUpload.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/quarantineServer.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/recycles.ts(6,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/redirect.ts(8,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/repeatNotification.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/resetPassword.ts(6,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/resetPassword.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/restoreProgress.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/saveLoginIp.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/saveLoginIp.ts(26,9): error TS2578: Unused '@ts-expect-error' directive.
#12 345.9 routes/search.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/securityQuestion.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/showProductReviews.ts(8,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/trackOrder.ts(8,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/updateProductReviews.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/updateUserProfile.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/userProfile.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/userProfile.ts(12,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/verify.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/verify.ts(9,52): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/juice-shop/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
#12 345.9 routes/verify.ts(14,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/verify.ts(15,17): error TS7016: Could not find a declaration file for module 'jws'. '/juice-shop/node_modules/jws/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/jws` if it exists or add a new declaration (.d.ts) file containing `declare module 'jws';`
#12 345.9 routes/verify.ts(409,15): error TS7006: Parameter 'product' implicitly has an 'any' type.
#12 345.9 routes/verify.ts(411,11): error TS7006: Parameter 'keyword' implicitly has an 'any' type.
#12 345.9 routes/videoHandler.ts(7,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/videoHandler.ts(9,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 routes/vulnCodeFixes.ts(1,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/vulnCodeSnippet.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/vulnCodeSnippet.ts(8,18): error TS7016: Could not find a declaration file for module 'js-yaml'. '/juice-shop/node_modules/js-yaml/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/js-yaml` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-yaml';`
#12 345.9 routes/wallet.ts(6,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 routes/web3Wallet.ts(1,45): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 server.ts(7,64): error TS7016: Could not find a declaration file for module 'express'. '/juice-shop/node_modules/express/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`
#12 345.9 server.ts(24,20): error TS7016: Could not find a declaration file for module 'config'. '/juice-shop/node_modules/config/lib/config.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/config` if it exists or add a new declaration (.d.ts) file containing `declare module 'config';`
#12 345.9 server.ts(26,20): error TS7016: Could not find a declaration file for module 'morgan'. '/juice-shop/node_modules/morgan/index.js' implicitly has an 'any' type.
#12 345.9   Try `npm i --save-dev @types/morgan` if it exists or add a new declaration (.d.ts) file containing `declare module 'morgan';`
#12 345.9 server.ts(236,5): error TS2578: Unused '@ts-expect-error' directive.
#12 345.9 server.ts(253,7): error TS2578: Unused '@ts-expect-error' directive.
#12 345.9 server.ts(303,5): error TS2578: Unused '@ts-expect-error' directive.
#12 346.0 
#12 346.0 added 1172 packages, and audited 1173 packages in 6m
#12 346.0 
#12 346.0 108 packages are looking for funding
#12 346.0   run `npm fund` for details
#12 346.1 
#12 346.1 36 vulnerabilities (1 low, 13 moderate, 15 high, 7 critical)
#12 346.1 
#12 346.1 To address issues that do not require attention, run:
#12 346.1   npm audit fix
#12 346.1 
#12 346.1 To address all issues possible (including breaking changes), run:
#12 346.1   npm audit fix --force
#12 346.1 
#12 346.1 Some issues need review, and may require choosing
#12 346.1 a different dependency.
#12 346.1 
#12 346.1 Run `npm audit` for details.
#12 DONE 347.7s
#13 [installer  6/18] RUN npm dedupe --omit=dev
#13 sha256:8b99f7855b05c647287f8972b7bb9f53e4e41e1ea9c468699b40bc009b5e8e01
#13 70.86 
#13 70.86 added 1 package, removed 8 packages, changed 6 packages, and audited 1166 packages in 1m
#13 70.86 
#13 70.86 108 packages are looking for funding
#13 70.86   run `npm fund` for details
#13 70.90 
#13 70.90 36 vulnerabilities (1 low, 13 moderate, 15 high, 7 critical)
#13 70.90 
#13 70.90 To address issues that do not require attention, run:
#13 70.90   npm audit fix
#13 70.90 
#13 70.90 To address all issues possible (including breaking changes), run:
#13 70.90   npm audit fix --force
#13 70.90 
#13 70.90 Some issues need review, and may require choosing
#13 70.90 a different dependency.
#13 70.90 
#13 70.90 Run `npm audit` for details.
#13 DONE 71.0s
#14 [installer  7/18] RUN rm -rf frontend/node_modules
#14 sha256:e3bf83bee6895a1380e61db2c8dd40a60a783c285fc20e99022f7442f039fe67
#14 DONE 3.3s
#15 [installer  8/18] RUN rm -rf frontend/.angular
#15 sha256:74c6a5d0e989cbf0041e3403e8a7053adc8312cfe2514293ddbfaf1cb105c606
#15 DONE 0.3s
#16 [installer  9/18] RUN rm -rf frontend/src/assets
#16 sha256:5a886111c4ca509142401cf828c23c1eb7e9a6103b8374f2ad1e5a630435af8a
#16 DONE 0.2s
#17 [installer 10/18] RUN mkdir logs
#17 sha256:e998372e38f9383547936eaf780b34ce07f34b73aa76fdd261674bf3d3eb906d
#17 DONE 0.3s
#18 [installer 11/18] RUN chown -R 65532 logs
#18 sha256:8319d3e1ba57daf288e4f4ec51a6f1c0283d5b794b523118f5e7361ebeaa4c61
#18 DONE 0.3s
#19 [installer 12/18] RUN chgrp -R 0 ftp/ frontend/dist/ logs/ data/ i18n/
#19 sha256:89813ea1cd8e6f7b302067694d15808ddfcf9c405e7a9fe9cd92fa3a6c1da7d3
#19 DONE 2.5s
#20 [installer 13/18] RUN chmod -R g=u ftp/ frontend/dist/ logs/ data/ i18n/
#20 sha256:a06ccf8dfce9c5cc7660529a1da2996a6d0942ba50cfd287398270040e1788fe
#20 DONE 2.6s
#21 [installer 14/18] RUN rm data/chatbot/botDefaultTrainingData.json || true
#21 sha256:a6cbe4b4566610d77ba8d5193402ffc277878ddd12d967bbd5fd1db3ee366709
#21 0.253 rm: cannot remove 'data/chatbot/botDefaultTrainingData.json': No such file or directory
#21 DONE 0.3s
#22 [installer 15/18] RUN rm ftp/legal.md || true
#22 sha256:3845aaf903686a396e33b1ceb14c038713b2023897e8aaab1f9e173f98cff4c7
#22 0.330 rm: cannot remove 'ftp/legal.md': No such file or directory
#22 DONE 0.4s
#23 [installer 16/18] RUN rm i18n/*.json || true
#23 sha256:a9b480bc0289965a074125e3bec879cfa16745c71dde5ea5b4a48b74be2d5d06
#23 0.248 rm: cannot remove 'i18n/*.json': No such file or directory
#23 DONE 0.3s
#24 [installer 17/18] RUN npm install -g @cyclonedx/cyclonedx-npm@latest
#24 sha256:cc9a30e7f2dca2a4c61852920ca4a419f8480d74d5e49b5613087cd8c1878cfc
#24 10.15 
#24 10.15 added 47 packages in 10s
#24 10.15 
#24 10.15 5 packages are looking for funding
#24 10.15   run `npm fund` for details
#24 DONE 10.3s
#25 [installer 18/18] RUN npm run sbom
#25 sha256:034a7d847b94cd7c7f02d27bc450a579a33531a04c437c6ef02037fbcd41d6ee
#25 0.371 
#25 0.371 > juice-shop@17.2.0 sbom
#25 0.371 > npm run sbom:json && npm run sbom:xml
#25 0.371 
#25 0.526 
#25 0.526 > juice-shop@17.2.0 sbom:json
#25 0.526 > cyclonedx-npm --omit=dev --output-format=JSON --output-file=bom.json
#25 0.526 
#25 10.61 
#25 10.61 > juice-shop@17.2.0 sbom:xml
#25 10.61 > cyclonedx-npm --omit=dev --output-format=XML  --output-file=bom.xml
#25 10.61 
#25 DONE 13.5s
#29 [libxmljs-builder 4/5] COPY --from=installer /juice-shop/node_modules ./node_modules
#29 sha256:cc2378d3e327faf53be0c3515cbdbbd990f79066293304a8e6dea49cd9ea3ca8
#29 ...
#26 [stage-2 3/4] COPY --from=installer --chown=65532:0 /juice-shop .
#26 sha256:9713f45adbb186db2fb5310fd2cdfbcac1c95a8e1dba1ae10794a0988e4667fb
#26 DONE 12.9s
#29 [libxmljs-builder 4/5] COPY --from=installer /juice-shop/node_modules ./node_modules
#29 sha256:cc2378d3e327faf53be0c3515cbdbbd990f79066293304a8e6dea49cd9ea3ca8
#29 DONE 13.2s
#30 [libxmljs-builder 5/5] RUN rm -rf node_modules/libxmljs/build &&   cd node_modules/libxmljs &&   npm run build
#30 sha256:7ec68a35e78ec96d233adaf1d3e27c0050e43ece828a295b2d2cec2ce89d0db8
#30 0.536 
#30 0.536 > libxmljs@1.0.11 build
#30 0.536 > node-gyp rebuild -j max
#30 0.536 
#30 0.592 gyp info it worked if it ends with ok
#30 0.593 gyp info using node-gyp@10.1.0
#30 0.593 gyp info using node@20.15.0 | linux | x64
#30 0.663 gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
#30 0.782 
#30 0.785 gyp http GET https://nodejs.org/download/release/v20.15.0/node-v20.15.0-headers.tar.gz
#30 0.901 gyp http 200 https://nodejs.org/download/release/v20.15.0/node-v20.15.0-headers.tar.gz
#30 2.483 gyp http GET https://nodejs.org/download/release/v20.15.0/SHASUMS256.txt
#30 2.517 gyp http 200 https://nodejs.org/download/release/v20.15.0/SHASUMS256.txt
#30 2.524 gyp info spawn /usr/bin/python3
#30 2.527 gyp info spawn args [
#30 2.527 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#30 2.527 gyp info spawn args 'binding.gyp',
#30 2.527 gyp info spawn args '-f',
#30 2.527 gyp info spawn args 'make',
#30 2.527 gyp info spawn args '-I',
#30 2.527 gyp info spawn args '/juice-shop/node_modules/libxmljs/build/config.gypi',
#30 2.527 gyp info spawn args '-I',
#30 2.527 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#30 2.527 gyp info spawn args '-I',
#30 2.527 gyp info spawn args '/root/.cache/node-gyp/20.15.0/include/node/common.gypi',
#30 2.527 gyp info spawn args '-Dlibrary=shared_library',
#30 2.527 gyp info spawn args '-Dvisibility=default',
#30 2.527 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.15.0',
#30 2.527 gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#30 2.527 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.15.0/<(target_arch)/node.lib',
#30 2.527 gyp info spawn args '-Dmodule_root_dir=/juice-shop/node_modules/libxmljs',
#30 2.527 gyp info spawn args '-Dnode_engine=v8',
#30 2.527 gyp info spawn args '--depth=.',
#30 2.527 gyp info spawn args '--no-parallel',
#30 2.527 gyp info spawn args '--generator-output',
#30 2.527 gyp info spawn args 'build',
#30 2.527 gyp info spawn args '-Goutput_dir=.'
#30 2.527 gyp info spawn args ]
#30 3.247 gyp info spawn make
#30 3.248 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 2 ]
#30 3.251 make: Entering directory '/juice-shop/node_modules/libxmljs/build'
#30 3.267   CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
#30 3.267   CXX(target) Release/obj.target/xmljs/src/libxml2.o
#30 4.319 ../src/xml_sax_parser.cc: In member function 'void libxmljs::XmlSaxParser::Callback(const char*, int, v8::Local<v8::Value>*)':
#30 4.319 ../src/xml_sax_parser.cc:120:37: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
#30 4.319                        argc + 1, args);
#30 4.319                                      ^
#30 4.319 In file included from ../src/xml_sax_parser.cc:3:
#30 4.319 ../../nan/nan.h:1044:46: note: declared here
#30 4.319    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
#30 4.319                                               ^~~~~~~~~~~~
#30 4.319 ../src/xml_sax_parser.cc:120:37: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
#30 4.319                        argc + 1, args);
#30 4.319                                      ^
#30 4.319 In file included from ../src/xml_sax_parser.cc:3:
#30 4.319 ../../nan/nan.h:1044:46: note: declared here
#30 4.319    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
#30 4.319                                               ^~~~~~~~~~~~
#30 5.066   CC(target) Release/obj.target/xmljs/vendor/libxml2/buf.o
#30 5.123 ../vendor/libxml2/buf.c: In function 'xmlBufMemoryError':
#30 5.124 ../vendor/libxml2/buf.c:94:5: warning: too many arguments for format [-Wformat-extra-args]
#30 5.124      __xmlSimpleError(XML_FROM_BUFFER, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 5.124      ^~~~~~~~~~~~~~~~
#30 5.124 ../vendor/libxml2/buf.c: In function 'xmlBufOverflowError':
#30 5.125 ../vendor/libxml2/buf.c:109:5: warning: too many arguments for format [-Wformat-extra-args]
#30 5.125      __xmlSimpleError(XML_FROM_BUFFER, XML_BUF_OVERFLOW, NULL, NULL, extra);
#30 5.125      ^~~~~~~~~~~~~~~~
#30 5.466   CC(target) Release/obj.target/xmljs/vendor/libxml2/catalog.o
#30 6.316   CC(target) Release/obj.target/xmljs/vendor/libxml2/chvalid.o
#30 6.413   CC(target) Release/obj.target/xmljs/vendor/libxml2/dict.o
#30 6.760   CC(target) Release/obj.target/xmljs/vendor/libxml2/encoding.o
#30 6.803 ../vendor/libxml2/encoding.c: In function 'xmlEncodingErrMemory':
#30 6.804 ../vendor/libxml2/encoding.c:86:5: warning: too many arguments for format [-Wformat-extra-args]
#30 6.804      __xmlSimpleError(XML_FROM_I18N, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 6.804      ^~~~~~~~~~~~~~~~
#30 6.820 ../vendor/libxml2/encoding.c: In function 'xmlCharEncCloseFunc':
#30 6.820 ../vendor/libxml2/encoding.c:2780:12: warning: variable 'handler_in_list' set but not used [-Wunused-but-set-variable]
#30 6.820      int i, handler_in_list = 0;
#30 6.820             ^~~~~~~~~~~~~~~
#30 7.865   CC(target) Release/obj.target/xmljs/vendor/libxml2/entities.o
#30 7.907 ../vendor/libxml2/entities.c: In function 'xmlEntitiesErrMemory':
#30 7.907 ../vendor/libxml2/entities.c:81:5: warning: too many arguments for format [-Wformat-extra-args]
#30 7.907      __xmlSimpleError(XML_FROM_TREE, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 7.907      ^~~~~~~~~~~~~~~~
#30 8.145   CC(target) Release/obj.target/xmljs/vendor/libxml2/error.o
#30 8.467   CC(target) Release/obj.target/xmljs/vendor/libxml2/globals.o
#30 8.681   CC(target) Release/obj.target/xmljs/vendor/libxml2/hash.o
#30 9.021   CC(target) Release/obj.target/xmljs/vendor/libxml2/HTMLparser.o
#30 10.74   CC(target) Release/obj.target/xmljs/vendor/libxml2/HTMLtree.o
#30 10.78 ../vendor/libxml2/HTMLtree.c: In function 'htmlSaveErrMemory':
#30 10.78 ../vendor/libxml2/HTMLtree.c:355:5: warning: too many arguments for format [-Wformat-extra-args]
#30 10.78      __xmlSimpleError(XML_FROM_OUTPUT, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 10.78      ^~~~~~~~~~~~~~~~
#30 11.02   CC(target) Release/obj.target/xmljs/vendor/libxml2/legacy.o
#30 11.31   CC(target) Release/obj.target/xmljs/vendor/libxml2/list.o
#30 11.50   CC(target) Release/obj.target/xmljs/vendor/libxml2/parser.o
#30 15.71   CC(target) Release/obj.target/xmljs/vendor/libxml2/parserInternals.o
#30 16.16   CC(target) Release/obj.target/xmljs/vendor/libxml2/pattern.o
#30 16.87   CC(target) Release/obj.target/xmljs/vendor/libxml2/relaxng.o
#30 19.45   CC(target) Release/obj.target/xmljs/vendor/libxml2/SAX2.o
#30 20.09   CC(target) Release/obj.target/xmljs/vendor/libxml2/SAX.o
#30 20.19   CC(target) Release/obj.target/xmljs/vendor/libxml2/tree.o
#30 20.23 ../vendor/libxml2/tree.c: In function 'xmlTreeErrMemory':
#30 20.23 ../vendor/libxml2/tree.c:80:5: warning: too many arguments for format [-Wformat-extra-args]
#30 20.23      __xmlSimpleError(XML_FROM_TREE, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 20.23      ^~~~~~~~~~~~~~~~
#30 22.57   CC(target) Release/obj.target/xmljs/vendor/libxml2/threads.o
#30 22.71   CC(target) Release/obj.target/xmljs/vendor/libxml2/uri.o
#30 23.41   CC(target) Release/obj.target/xmljs/vendor/libxml2/valid.o
#30 25.02   CC(target) Release/obj.target/xmljs/vendor/libxml2/xinclude.o
#30 25.10   CC(target) Release/obj.target/xmljs/vendor/libxml2/xlink.o
#30 25.20   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlIO.o
#30 25.25 ../vendor/libxml2/xmlIO.c: In function 'xmlIOErrMemory':
#30 25.25 ../vendor/libxml2/xmlIO.c:234:5: warning: too many arguments for format [-Wformat-extra-args]
#30 25.25      __xmlSimpleError(XML_FROM_IO, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 25.25      ^~~~~~~~~~~~~~~~
#30 25.67   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlmemory.o
#30 25.84   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlmodule.o
#30 25.95   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlreader.o
#30 25.99   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlregexp.o
#30 27.94   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlsave.o
#30 27.98 ../vendor/libxml2/xmlsave.c: In function 'xmlSaveErrMemory':
#30 27.99 ../vendor/libxml2/xmlsave.c:110:5: warning: too many arguments for format [-Wformat-extra-args]
#30 27.99      __xmlSimpleError(XML_FROM_OUTPUT, XML_ERR_NO_MEMORY, NULL, NULL, extra);
#30 27.99      ^~~~~~~~~~~~~~~~
#30 28.55   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlschemas.o
#30 28.60 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaPSimpleErr':
#30 28.60 ../vendor/libxml2/xmlschemas.c:1915:22: warning: too many arguments for format [-Wformat-extra-args]
#30 28.60                       msg);
#30 28.60                       ^~~
#30 28.60 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaPErrMemory':
#30 28.60 ../vendor/libxml2/xmlschemas.c:1932:22: warning: too many arguments for format [-Wformat-extra-args]
#30 28.60                       extra);
#30 28.60                       ^~~~~
#30 28.61 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaVErrMemory':
#30 28.61 ../vendor/libxml2/xmlschemas.c:2056:22: warning: too many arguments for format [-Wformat-extra-args]
#30 28.61                       extra);
#30 28.61                       ^~~~~
#30 28.63 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaPValAttrNodeQNameValue':
#30 28.63 ../vendor/libxml2/xmlschemas.c:5888:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.63       NULL, value, NULL, NULL, NULL);
#30 28.63       ^~~~
#30 28.64 ../vendor/libxml2/xmlschemas.c: In function 'xmlGetMaxOccurs':
#30 28.64 ../vendor/libxml2/xmlschemas.c:6104:3: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64    val, NULL, NULL, NULL);
#30 28.64    ^~~
#30 28.64 ../vendor/libxml2/xmlschemas.c:6118:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       val, NULL, NULL, NULL);
#30 28.64       ^~~
#30 28.64 ../vendor/libxml2/xmlschemas.c:6144:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       val, NULL, NULL, NULL);
#30 28.64       ^~~
#30 28.64 ../vendor/libxml2/xmlschemas.c: In function 'xmlGetMinOccurs':
#30 28.64 ../vendor/libxml2/xmlschemas.c:6179:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       val, NULL, NULL, NULL);
#30 28.64       ^~~
#30 28.64 ../vendor/libxml2/xmlschemas.c:6205:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       val, NULL, NULL, NULL);
#30 28.64       ^~~
#30 28.64 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaPGetBoolNodeValue':
#30 28.64 ../vendor/libxml2/xmlschemas.c:6249:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       NULL, NULL, NULL);
#30 28.64       ^~~~
#30 28.64 ../vendor/libxml2/xmlschemas.c: In function 'xmlGetBooleanProp':
#30 28.64 ../vendor/libxml2/xmlschemas.c:6297:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       NULL, val, NULL, NULL, NULL);
#30 28.64       ^~~~
#30 28.64 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaPValAttrNodeValue':
#30 28.64 ../vendor/libxml2/xmlschemas.c:6401:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.64       type, NULL, value, NULL, NULL, NULL);
#30 28.64       ^~~~
#30 28.65 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseWildcardNs':
#30 28.65 ../vendor/libxml2/xmlschemas.c:6834:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.65       NULL, NULL, NULL);
#30 28.65       ^~~~
#30 28.65 ../vendor/libxml2/xmlschemas.c:6872:7: warning: too many arguments for format [-Wformat-extra-args]
#30 28.65        nsItem, NULL, NULL, NULL);
#30 28.65        ^~~~~~
#30 28.66 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseLocalAttribute':
#30 28.66 ../vendor/libxml2/xmlschemas.c:7259:8: warning: too many arguments for format [-Wformat-extra-args]
#30 28.66         attrValue, NULL, NULL, NULL);
#30 28.66         ^~~~~~~~~
#30 28.66 ../vendor/libxml2/xmlschemas.c:7279:4: warning: too many arguments for format [-Wformat-extra-args]
#30 28.66     attrValue, NULL, NULL, NULL);
#30 28.66     ^~~~~~~~~
#30 28.68 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseElement':
#30 28.68 ../vendor/libxml2/xmlschemas.c:8700:4: warning: too many arguments for format [-Wformat-extra-args]
#30 28.68     attrValue, NULL, NULL, NULL);
#30 28.68     ^~~~~~~~~
#30 28.68 ../vendor/libxml2/xmlschemas.c:8779:4: warning: too many arguments for format [-Wformat-extra-args]
#30 28.68     attrValue, NULL, NULL, NULL);
#30 28.68     ^~~~~~~~~
#30 28.68 ../vendor/libxml2/xmlschemas.c:8809:7: warning: too many arguments for format [-Wformat-extra-args]
#30 28.68        NULL, NULL, NULL);
#30 28.68        ^~~~
#30 28.69 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseSimpleType':
#30 28.69 ../vendor/libxml2/xmlschemas.c:9365:7: warning: too many arguments for format [-Wformat-extra-args]
#30 28.69        attrValue, NULL, NULL, NULL);
#30 28.69        ^~~~~~~~~
#30 28.70 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseSchemaElement':
#30 28.70 ../vendor/libxml2/xmlschemas.c:9764:3: warning: too many arguments for format [-Wformat-extra-args]
#30 28.70    "(qualified | unqualified)", val, NULL, NULL, NULL);
#30 28.70    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#30 28.70 ../vendor/libxml2/xmlschemas.c:9777:3: warning: too many arguments for format [-Wformat-extra-args]
#30 28.70    "(qualified | unqualified)", val, NULL, NULL, NULL);
#30 28.70    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#30 28.70 ../vendor/libxml2/xmlschemas.c:9795:3: warning: too many arguments for format [-Wformat-extra-args]
#30 28.70    val, NULL, NULL, NULL);
#30 28.70    ^~~
#30 28.70 ../vendor/libxml2/xmlschemas.c:9811:3: warning: too many arguments for format [-Wformat-extra-args]
#30 28.70    val, NULL, NULL, NULL);
#30 28.70    ^~~
#30 28.73 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseImport':
#30 28.73 ../vendor/libxml2/xmlschemas.c:10833:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.73       NULL, namespaceName, NULL, NULL, NULL);
#30 28.73       ^~~~
#30 28.73 ../vendor/libxml2/xmlschemas.c:10844:6: warning: too many arguments for format [-Wformat-extra-args]
#30 28.73       NULL, schemaLocation, NULL, NULL, NULL);
#30 28.73       ^~~~
#30 28.75 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaParseComplexType':
#30 28.75 ../vendor/libxml2/xmlschemas.c:12303:8: warning: too many arguments for format [-Wformat-extra-args]
#30 28.75         attrValue, NULL, NULL, NULL);
#30 28.75         ^~~~~~~~~
#30 28.75 ../vendor/libxml2/xmlschemas.c:12321:8: warning: too many arguments for format [-Wformat-extra-args]
#30 28.75         attrValue, NULL, NULL, NULL);
#30 28.75         ^~~~~~~~~
#30 29.07 ../vendor/libxml2/xmlschemas.c: In function 'xmlSchemaValidateFacets':
#30 29.07 ../vendor/libxml2/xmlschemas.c:24468:3: warning: too many arguments for format [-Wformat-extra-args]
#30 29.07    value, len, type, facetLink->facet, NULL, NULL, NULL);
#30 29.07    ^~~~~
#30 29.08 ../vendor/libxml2/xmlschemas.c:24504:3: warning: too many arguments for format [-Wformat-extra-args]
#30 29.08    value, length, type, facetLink->facet, NULL, NULL, NULL);
#30 29.08    ^~~~~
#30 29.08 ../vendor/libxml2/xmlschemas.c:24555:17: warning: too many arguments for format [-Wformat-extra-args]
#30 29.08                  value, 0, type, NULL, NULL, NULL, NULL);
#30 29.08                  ^~~~~
#30 29.09 ../vendor/libxml2/xmlschemas.c:24597:21: warning: too many arguments for format [-Wformat-extra-args]
#30 29.09                      value, 0, type, facet, NULL, NULL, NULL);
#30 29.09                      ^~~~~
#30 35.31   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlschemastypes.o
#30 35.37 ../vendor/libxml2/xmlschemastypes.c: In function 'xmlSchemaTypeErrMemory':
#30 35.37 ../vendor/libxml2/xmlschemastypes.c:209:5: warning: too many arguments for format [-Wformat-extra-args]
#30 35.37      __xmlSimpleError(XML_FROM_DATATYPE, XML_ERR_NO_MEMORY, node, NULL, extra);
#30 35.37      ^~~~~~~~~~~~~~~~
#30 36.90   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlstring.o
#30 37.17   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlunicode.o
#30 37.47   CC(target) Release/obj.target/xmljs/vendor/libxml2/xmlwriter.o
#30 37.54   CC(target) Release/obj.target/xmljs/vendor/libxml2/xpath.o
#30 41.22   CC(target) Release/obj.target/xmljs/vendor/libxml2/xpointer.o
#30 48.63   SOLINK(target) Release/obj.target/xmljs.node
#30 48.90   COPY Release/xmljs.node
#30 48.91 make: Leaving directory '/juice-shop/node_modules/libxmljs/build'
#30 48.91 gyp info ok 
#30 48.93 npm notice
#30 48.93 npm notice New major version of npm available! 10.7.0 -> 11.2.0
#30 48.93 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.2.0
#30 48.93 npm notice To update run: npm install -g npm@11.2.0
#30 48.93 npm notice
#30 DONE 49.0s
#31 [stage-2 4/4] COPY --chown=65532:0 --from=libxmljs-builder /juice-shop/node_modules/libxmljs ./node_modules/libxmljs
#31 sha256:af3f977673d3996f6c2074ef18ed0ea63b5e6e00265bd526a8ef4312fd593337
#31 DONE 0.2s
#32 exporting to image
#32 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#32 exporting layers
#32 exporting layers 3.9s done
#32 writing image sha256:3bc5ae7d1d23b5749d0fbedca3ff7cd8ddbcdef09570520832af4b90ce25f5e9 done
#32 naming to docker.io/library/juice-shop:96f770ac4f24bfbc513e0e326bf3063f34d5dd33 done
#32 DONE 4.0s
$ mkdir -p ${REPORT_PATH}/docker
$ docker save juice-shop:$CI_COMMIT_SHA > ${REPORT_PATH}/docker/juice-shop.tar
Uploading artifacts for successful job
00:18
Uploading artifacts...
Dockerfile: found 1 matching artifact files and directories 
reports/docker/juice-shop.tar: found 1 matching artifact files and directories 
Uploading artifacts as "archive" to coordinator... 201 Created  id=9563812654 responseStatus=201 Created token=66_Fs_EHW
Cleaning up project directory and file based variables
00:01
Job succeeded
