Running with gitlab-runner 17.10.0~pre.41.g5c23fd8e (5c23fd8e)
  on blue-4.saas-linux-small-amd64.runners-manager.gitlab.com/default J2nyww-s, system ID: s_cf1798852952
Preparing the "docker+machine" executor
00:09
Using Docker executor with image registry.gitlab.com/security-products/semgrep:5 ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/security-products/semgrep:5 ...
Using docker image sha256:8ae9bf74553bb4354ef8de180fa138a0aff821d3ad28351098a71ab26754e640 for registry.gitlab.com/security-products/semgrep:5 with digest registry.gitlab.com/security-products/semgrep@sha256:e0dfd100f7e7d7a25731f1335f3621c967bfd32384f9e42130f44dcdd671e871 ...
Preparing environment
00:03
Running on runner-j2nyww-s-project-68482359-concurrent-0 via runner-j2nyww-s-s-l-s-amd64-1743228171-9eb5b288...
Getting source from Git repository
00:03
Fetching changes with git depth set to 1...
Initialized empty Git repository in /builds/qlkwej-org/test-ci-cd-juice-shop/.git/
Created fresh repository.
Checking out 96f770ac as detached HEAD (ref is master)...
Skipping Git submodules setup
$ git remote set-url origin "${CI_REPOSITORY_URL}" || echo 'Not a git repository; skipping'
Executing "step_script" stage of the job script
00:36
Using docker image sha256:8ae9bf74553bb4354ef8de180fa138a0aff821d3ad28351098a71ab26754e640 for registry.gitlab.com/security-products/semgrep:5 with digest registry.gitlab.com/security-products/semgrep@sha256:e0dfd100f7e7d7a25731f1335f3621c967bfd32384f9e42130f44dcdd671e871 ...
$ /analyzer run
[DEBUG] ▶ Choosing the input analyzer report: '/builds/qlkwej-org/test-ci-cd-juice-shop/gl-sast-report.json'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/command.go:79] ▶ GitLab Semgrep analyzer v5.30.0
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ ANALYZER_TARGET_DIR,CI_PROJECT_DIR=/builds/qlkwej-org/test-ci-cd-juice-shop
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ ANALYZER_ARTIFACT_DIR,CI_PROJECT_DIR=/builds/qlkwej-org/test-ci-cd-juice-shop
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ ANALYZER_INDENT_REPORT=false
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ ANALYZER_OPTIMIZE_REPORT=true
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ ADDITIONAL_CA_CERT_BUNDLE=
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SEARCH_IGNORED_DIRS=bundle,node_modules,vendor,tmp,test,tests
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SEARCH_IGNORE_HIDDEN_DIRS=true
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SEARCH_MAX_DEPTH=20
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SAST_SEMGREP_METRICS=true
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SAST_EXPERIMENTAL_FEATURES=false
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SAST_EXCLUDED_PATHS=spec, test, tests, tmp
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SAST_SCANNER_ALLOWED_CLI_OPTS=
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:267] ▶ SAST_EXCLUDED_PATHS=spec,test,tests,tmp
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/common/v3@v3.4.0/cacert/cacert.go:65] ▶ CA cert bundle not imported: empty bundle or empty target path
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:131] ▶ Detecting project
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:153] ▶ Analyzer will attempt to analyze all projects in the repository
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:165] ▶ Loading ruleset for /builds/qlkwej-org/test-ci-cd-juice-shop
[WARN] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/ruleset/v3@v3.3.1/ruleset.go:263] ▶ /builds/qlkwej-org/test-ci-cd-juice-shop/.gitlab/sast-ruleset.toml not found, ruleset customization will be disabled.
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:175] ▶ Running analyzer
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/gitlab/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/lgpl/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/lgpl-cc/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/manifest.json
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:214] ▶ 22 active rule files detected with 591 active rules
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/bandit.yml': '72330bf43a0bd72cad5def235287fbb284d3fd4ae5bf83e2e132e4beee75ce6f'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/eslint.yml': '23d4577a285789a9e6763af02cebcae53fc9102e9a9a6c070fe3aaf4d0f76184'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/find_sec_bugs.yml': '49d99dc98afef978cc7ec933a0590b72961ef695d74db87ba505f3c09827ea6f'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/find_sec_bugs_scala.yml': '97a92134cb8fcba6f48da8e7af444acc5368172883b42deb1e250ee2360418ab'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/flawfinder.yml': '41e51007ef30f34fc4e0cbd13e75598e002330b52ab635257baca967eedae5a4'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gitlab/gitlab_ee_generic.yml': '15abc845364e9f98a026ad44075cce1957db8e7e963751ebfb1b5e60fb82059e'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gitlab/gitlab_ee_java.yml': '5e5e2b260f5e80c1f97d0f9d09115875127d6b6f35f05b3ac339b1f0112800d1'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gitlab/gitlab_ee_javascript.yml': 'f4b83bc90c77fad8bd56bcb9abe53c8467b44875ecbdbaccb040fccbb58e2a49'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gitlab_ce_python.yml': 'fd40f79402659b687a3d43d53895ab85a4186e95b9b022dd368642852f064cb5'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gitlab_ce_scala.yml': '5c1522e888fe5eecb1c8679f2de4a7cec35beedf47848113574654759f5ca396'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/gosec.yml': '0497a5a5b64f012c16000e96cd6ab12fa7f5e2ed5c771ce0c5fba30a27bc5423'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/brakeman.yml': '53af0d542d05fe74649071ac3905d602fd24684fafd68f183b44283e84143a37'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/gitlab_lgpl_cc_java.yml': 'f3510e15f79e0c85700efa5496cf7053646e86a081c6aafe41e35bdd9a9c6ce1'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/gitlab_lgpl_cc_javascript.yml': '38f732a386b63269972f430321875fe722e4bc4c293c80113ffd605f11110b46'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/gitlab_lgpl_cc_properties.yml': 'fc2c7308e5122deaff902dbe3ea202256a7f89071b7a1a7303d19016414e6030'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/gitlab_lgpl_cc_python.yml': 'a4f8d8f27199984d13a0d7e0957050de5d730174957dc2396e07c219502fb4b8'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/gitlab_lgpl_cc_yaml.yml': '822fb6b095bc0259fcba1c03a32d661924222beccb0c1c6eda7a86d5d619c0c0'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl-cc/phpcs_security_audit.yml': '35d202a7427c2cc82e79d234872258d575d6fa66178a83776b3aa716389b98a0'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl/find_sec_bugs_kotlin.yml': '3d674e5655c22939ec1b869bf229887da3710ef8256ff2321a954ba15261d7c3'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl/mobsf.yml': 'f4a44c39525e2590d8ab026600a4c678bb4ec664db1acc0b5227a92e37210b93'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/lgpl/nodejs_scan.yml': '68ef90cb45019ff2bce87629d608a063f9e738a9449714f02f24ed7122caedf9'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:220] ▶  * rule file '/rules/security_code_scan.yml': 'fec26e216ce7a2ba4e22285be3b60627e0b7e5b5d6fdd68e86ef1548aa3d5c7c'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:222] ▶ Combined rule checksum: '8af77b2e56bde58bfef06321118517ffe8ae41ab71cc43e6835dcb2d02851a6d'
[INFO] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/rules/ruleinfo.go:232] ▶ Using the GitLab SAST default ruleset
[DEBU] [Semgrep] [2025-03-29T06:03:48Z] [/go/src/buildapp/analyze.go:100] ▶ /usr/local/bin/semgrep -f /rules -o /builds/qlkwej-org/test-ci-cd-juice-shop/semgrep.sarif --sarif --no-rewrite-rule-ids --strict --disable-version-check --no-git-ignore --exclude spec --exclude test --exclude tests --exclude tmp --metrics on --verbose
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ To disable Registry rule metrics, use "--metrics=off".
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ Using configs only from local files (like --config=xyz.yml) does not enable metrics.
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ More information: https://semgrep.dev/docs/metrics
[INFO] [Semgrep] [2025-03-29T06:03:49Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ running 591 rules from 22 configs
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Using explicit semgrepignore file from environment variable
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Rules:
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ <SKIPPED DATA (too many entries; use --max-log-list-entries)>
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring frontend/src/assets/private/dat.gui.min.js due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring frontend/src/assets/private/stats.min.js due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring .gitignore due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring frontend/.gitignore due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring frontend/src/assets/private/dat.gui.min.js due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ Ignoring frontend/src/assets/private/stats.min.js due to .semgrepignore
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶                
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶                
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ ┌─────────────┐
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ │ Scan Status │
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶ └─────────────┘
[INFO] [Semgrep] [2025-03-29T06:03:56Z] ▶   Scanning 1168 files with 591 Code rules:
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶                                                                                                                         
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶   Language      Rules   Files          Origin   Rules                                                                   
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶  ─────────────────────────────        ────────────────                                                                  
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶   <multilang>       1     482          Custom     591                                                                   
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶   ts               96     468                                                                                           
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶   yaml              1      85                                                                                           
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶   js               96      14                                                                                           
[INFO] [Semgrep] [2025-03-29T06:03:57Z] ▶                                                                                                                         
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ ========================================
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ Files skipped:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ ========================================
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Always skipped by Semgrep:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/FETCH_HEAD
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/HEAD
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/config
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/index
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/logs/HEAD
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/logs/refs/remotes/origin/master
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/objects/pack/pack-50cdbfce095f72d9ae8e047424ead67b64643dd0.idx
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/objects/pack/pack-50cdbfce095f72d9ae8e047424ead67b64643dd0.pack
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/objects/pack/pack-50cdbfce095f72d9ae8e047424ead67b64643dd0.rev
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/refs/pipelines/1741529340
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/refs/remotes/origin/master
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .git/shallow
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Skipped by .gitignore:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   (Disabled with --no-git-ignore)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • <none>
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Skipped by .semgrepignore:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   - https://semgrep.dev/docs/ignoring-files-folders-code/#understand-semgrep-defaults
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • .gitignore
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/.gitignore
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/dat.gui.min.js
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/stats.min.js
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Skipped by --include patterns:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • <none>
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Skipped by --exclude patterns:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • <SKIPPED DATA (too many entries; use --max-log-list-entries)>
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Files that couldn't be accessed:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • <none>
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Skipped by limiting to files smaller than 1000000 bytes:
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   (Adjust with the --max-target-bytes flag)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/earth_normalmap_flat4k.jpg
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/fair_clouds_4k.png
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/starry_background.jpg
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/public/images/products/20th.jpeg
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/public/images/uploads/IMG_4253.jpg
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/public/videos/owasp_promo.mp4
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • screenshots/screenshot07.png
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • screenshots/slideshow.gif
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Partially analyzed due to parsing or internal Semgrep errors
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginAdminChallenge_1.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginAdminChallenge_2.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginAdminChallenge_3.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginAdminChallenge_4_correct.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginBenderChallenge_1.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginBenderChallenge_2_correct.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginBenderChallenge_3.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginBenderChallenge_4.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginJimChallenge_1_correct.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginJimChallenge_2.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginJimChallenge_3.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/loginJimChallenge_4.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/registerAdminChallenge_1.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/registerAdminChallenge_2.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/registerAdminChallenge_3_correct.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/registerAdminChallenge_4.ts
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/restfulXssChallenge_2.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/restfulXssChallenge_3.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/restfulXssChallenge_4.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/tokenSaleChallenge_1.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/tokenSaleChallenge_2.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/tokenSaleChallenge_3_correct.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/weakPasswordChallenge_1_correct.ts (9 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/weakPasswordChallenge_2.ts (13 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/weakPasswordChallenge_3.ts (12 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • data/static/codefixes/weakPasswordChallenge_4.ts (8 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/app/Services/user.service.ts (1 lines skipped)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • frontend/src/assets/private/three.js with 3 rules (e.g. nodejs_scan.javascript-redirect-rule-
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶      express_open_redirect2)
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶    • server.ts with rule nodejs_scan.javascript-dos-rule-regex_dos
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶                 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶                 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ ┌──────────────┐
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ │ Scan Summary │
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ └──────────────┘
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ Some files were skipped or only partially analyzed.
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Partially scanned: 29 files only partially analyzed due to parsing or internal Semgrep errors
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   Scan skipped: 137 files matching --exclude patterns, 8 files larger than 1.0 MB, 4 files matching .semgrepignore patterns
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶   For a full list of skipped files, run semgrep with the --verbose flag.
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ 
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ Ran 98 rules on 567 files: 79 findings.
[INFO] [Semgrep] [2025-03-29T06:04:22Z] ▶ Sending pseudonymous metrics since metrics are configured to ON and registry usage is False
[INFO] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/run.go:189] ▶ Creating report
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/src/buildapp/convert.go:43] ▶ Converting report with the root path: /builds/qlkwej-org/test-ci-cd-juice-shop
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginAdminChallenge_1.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    if (req.body.email.match(/.*['-;].*/) || req.body.password.match(/.*['-;].*/)) {
      res.status(451).send(res.__('SQL Injection detected.'))
    }
    models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginAdminChallenge_2.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = $1 AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`,
      { bind: [ req.body.email ], model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginAdminChallenge_3.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = $1 AND password = $2 AND deletedAt IS NULL`,
      { bind: [ req.body.email, req.body.password ], model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginAdminChallenge_4_correct.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = $1 AND password = $2 AND deletedAt IS NULL`,
      { bind: [ req.body.email, security.hash(req.body.password) ], model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginBenderChallenge_1.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    if (req.body.email.match(/.*['-;].*/) || req.body.password.match(/.*['-;].*/)) {
      res.status(451).send(res.__('SQL Injection detected.'))
    }
    models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginBenderChallenge_2_correct.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = $mail AND password = $pass AND deletedAt IS NULL`,
      { bind: { mail: req.body.email, pass: security.hash(req.body.password) }, model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginBenderChallenge_3.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = :mail AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`,
      { replacements: { mail: req.body.email }, model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginBenderChallenge_4.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: models.User, plain: false })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginJimChallenge_1_correct.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = $1 AND password = $2 AND deletedAt IS NULL`,
      { bind: [ req.body.email, security.hash(req.body.password) ], model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginJimChallenge_2.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: models.User, plain: false })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginJimChallenge_3.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    models.sequelize.query(`SELECT * FROM Users WHERE email = ? AND password = ? AND deletedAt IS NULL`,
      { replacements: [ req.body.email, req.body.password ], model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/loginJimChallenge_4.ts:1:
 `import {BasketModel} from "../../../models/basket";
module.exports = function login () {
  function afterLogin (user: { data: User, bid: number }, res: Response, next: NextFunction) {
    BasketModel.findOrCreate({ where: { UserId: user.data.id } })
      .then(([basket]: [BasketModel, boolean]) => {
        const token = security.authorize(user)
        user.bid = basket.id // keep track of original basket
        security.authenticatedUsers.put(token, user)
        res.json({ authentication: { token, bid: basket.id, umail: user.data.email } })
      }).catch((error: Error) => {
        next(error)
      })
  }
  return (req: Request, res: Response, next: NextFunction) => {
    if (req.body.email.match(/.*['-;].*/) || req.body.password.match(/.*['-;].*/)) {
      res.status(451).send(res.__('SQL Injection detected.'))
    }
    models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: models.User, plain: true })
      .then((authenticatedUser) => {
        const user = utils.queryResultToJson(authenticatedUser)
        if (user.data?.id && user.data.totpSecret !== '') {
          res.status(401).json({
            status: 'totp_token_required',
            data: {
              tmpToken: security.authorize({
                userId: user.data.id,
                type: 'password_valid_needs_second_factor_token'
              })
            }
          })
        } else if (user.data?.id) {
          afterLogin(user, res, next)
        } else {
          res.status(401).send(res.__('Invalid email or password.'))
        }
      }).catch((error: Error) => {
        next(error)
      })
  }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/registerAdminChallenge_1.ts:1:
 `/* Generated API endpoints */
  finale.initialize({ app, sequelize })
  const autoModels = [
    { name: 'User', exclude: ['password', 'totpSecret'], model: UserModel },
    { name: 'Product', exclude: [], model: ProductModel },
    { name: 'Feedback', exclude: [], model: FeedbackModel },
    { name: 'BasketItem', exclude: [], model: BasketItemModel },
    { name: 'Challenge', exclude: [], model: ChallengeModel },
    { name: 'Complaint', exclude: [], model: ComplaintModel },
    { name: 'Recycle', exclude: [], model: RecycleModel },
    { name: 'SecurityQuestion', exclude: [], model: SecurityQuestionModel },
    { name: 'SecurityAnswer', exclude: [], model: SecurityAnswerModel },
    { name: 'Address', exclude: [], model: AddressModel },
    { name: 'PrivacyRequest', exclude: [], model: PrivacyRequestModel },
    { name: 'Card', exclude: [], model: CardModel },
    { name: 'Quantity', exclude: [], model: QuantityModel }
  ]
  for (const { name, exclude, model } of autoModels) {
    const resource = finale.resource({
      model,
      endpoints: [`/api/${name}s`, `/api/${name}s/:id`],
      excludeAttributes: exclude,
      pagination: false
    })
    // create a wallet when a new user is registered using API
    if (name === 'User') {
      resource.create.send.before((req: Request, res: Response, context: { instance: { id: any }, continue: any }) => {
        WalletModel.create({ UserId: context.instance.id }).catch((err: unknown) => {
          console.log(err)
        })
        context.instance.role = context.instance.role ? context.instance.role : 'customer'
        return context.continue
      })
    }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/registerAdminChallenge_2.ts:1:
 `/* Generated API endpoints */
  finale.initialize({ app, sequelize })
  const autoModels = [
    { name: 'Product', exclude: [], model: ProductModel },
    { name: 'Feedback', exclude: [], model: FeedbackModel },
    { name: 'BasketItem', exclude: [], model: BasketItemModel },
    { name: 'Challenge', exclude: [], model: ChallengeModel },
    { name: 'Complaint', exclude: [], model: ComplaintModel },
    { name: 'Recycle', exclude: [], model: RecycleModel },
    { name: 'SecurityQuestion', exclude: [], model: SecurityQuestionModel },
    { name: 'SecurityAnswer', exclude: [], model: SecurityAnswerModel },
    { name: 'Address', exclude: [], model: AddressModel },
    { name: 'PrivacyRequest', exclude: [], model: PrivacyRequestModel },
    { name: 'Card', exclude: [], model: CardModel },
    { name: 'Quantity', exclude: [], model: QuantityModel }
  ]
  for (const { name, exclude, model } of autoModels) {
    const resource = finale.resource({
      model,
      endpoints: [`/api/${name}s`, `/api/${name}s/:id`],
      excludeAttributes: exclude,
      pagination: false
    })` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/registerAdminChallenge_3_correct.ts:1:
 `/* Generated API endpoints */
  finale.initialize({ app, sequelize })
  const autoModels = [
    { name: 'User', exclude: ['password', 'totpSecret'], model: UserModel },
    { name: 'Product', exclude: [], model: ProductModel },
    { name: 'Feedback', exclude: [], model: FeedbackModel },
    { name: 'BasketItem', exclude: [], model: BasketItemModel },
    { name: 'Challenge', exclude: [], model: ChallengeModel },
    { name: 'Complaint', exclude: [], model: ComplaintModel },
    { name: 'Recycle', exclude: [], model: RecycleModel },
    { name: 'SecurityQuestion', exclude: [], model: SecurityQuestionModel },
    { name: 'SecurityAnswer', exclude: [], model: SecurityAnswerModel },
    { name: 'Address', exclude: [], model: AddressModel },
    { name: 'PrivacyRequest', exclude: [], model: PrivacyRequestModel },
    { name: 'Card', exclude: [], model: CardModel },
    { name: 'Quantity', exclude: [], model: QuantityModel }
  ]
  for (const { name, exclude, model } of autoModels) {
    const resource = finale.resource({
      model,
      endpoints: [`/api/${name}s`, `/api/${name}s/:id`],
      excludeAttributes: exclude,
      pagination: false
    })
    // create a wallet when a new user is registered using API
    if (name === 'User') {
      resource.create.send.before((req: Request, res: Response, context: { instance: { id: any }, continue: any }) => {
        WalletModel.create({ UserId: context.instance.id }).catch((err: unknown) => {
          console.log(err)
        })
        context.instance.role = 'customer'
        return context.continue
      })
    }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/registerAdminChallenge_4.ts:1:
 `/* Generated API endpoints */
  finale.initialize({ app, sequelize })
  const autoModels = [
    { name: 'User', exclude: ['password', 'totpSecret', 'role'], model: UserModel },
    { name: 'Product', exclude: [], model: ProductModel },
    { name: 'Feedback', exclude: [], model: FeedbackModel },
    { name: 'BasketItem', exclude: [], model: BasketItemModel },
    { name: 'Challenge', exclude: [], model: ChallengeModel },
    { name: 'Complaint', exclude: [], model: ComplaintModel },
    { name: 'Recycle', exclude: [], model: RecycleModel },
    { name: 'SecurityQuestion', exclude: [], model: SecurityQuestionModel },
    { name: 'SecurityAnswer', exclude: [], model: SecurityAnswerModel },
    { name: 'Address', exclude: [], model: AddressModel },
    { name: 'PrivacyRequest', exclude: [], model: PrivacyRequestModel },
    { name: 'Card', exclude: [], model: CardModel },
    { name: 'Quantity', exclude: [], model: QuantityModel }
  ]
  for (const { name, exclude, model } of autoModels) {
    const resource = finale.resource({
      model,
      endpoints: [`/api/${name}s`, `/api/${name}s/:id`],
      excludeAttributes: exclude,
      pagination: false
    })
    // create a wallet when a new user is registered using API
    if (name === 'User') {
      resource.create.send.before((req: Request, res: Response, context: { instance: { id: any }, continue: any }) => {
        WalletModel.create({ UserId: context.instance.id }).catch((err: unknown) => {
          console.log(err)
        })
        return context.continue
      })
    }` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/restfulXssChallenge_2.ts:57:
 `: any[]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/restfulXssChallenge_3.ts:43:
 `: any[]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/restfulXssChallenge_4.ts:57:
 `: any[]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/tokenSaleChallenge_1.ts:18:
 `]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/tokenSaleChallenge_2.ts:19:
 `]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/tokenSaleChallenge_3_correct.ts:14:
 `]` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/weakPasswordChallenge_1_correct.ts:1:
 `User.init(
      password: {
        type: DataTypes.STRING,
        set (clearTextPassword: string) {
          validatePasswordHasAtLeastTenChar(clearTextPassword)
          validatePasswordIsNotInTopOneMillionCommonPasswordsList(clearTextPassword)
          this.setDataValue('password', security.hash(clearTextPassword))
        }
      },` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/weakPasswordChallenge_2.ts:1:
 `User.init(
      password: {
        type: DataTypes.STRING,
        set (clearTextPassword: string) {
          validatePasswordHasAtLeastOneNumber(clearTextPassword)
          validatePasswordHasAtLeastOneSpecialChar(clearTextPassword)
          validatePasswordHasAtLeastOneUpperCaseChar(clearTextPassword)
          validatePasswordHasAtLeastOneLowerCaseChar(clearTextPassword)
          validatePasswordHasAtLeastTenChar(clearTextPassword)
          validatePasswordIsNotInTopOneMillionCommonPasswordsList(clearTextPassword)
          this.setDataValue('password', security.hash(clearTextPassword))
        }
      },` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/weakPasswordChallenge_3.ts:1:
 `User.init(
      password: {
        type: DataTypes.STRING,
        set (clearTextPassword: string) {
          validatePasswordHasAtLeastOneNumber(clearTextPassword)
          validatePasswordHasAtLeastOneSpecialChar(clearTextPassword)
          validatePasswordHasAtLeastOneUpperCaseChar(clearTextPassword)
          validatePasswordHasAtLeastOneLowerCaseChar(clearTextPassword)
          validatePasswordHasAtLeastTenChar(clearTextPassword)
          this.setDataValue('password', security.hash(clearTextPassword))
        }
      },` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line data/static/codefixes/weakPasswordChallenge_4.ts:1:
 `User.init(
      password: {
        type: DataTypes.STRING,
        set (clearTextPassword: string) {
          validatePasswordIsNotInTopOneMillionCommonPasswordsList(clearTextPassword)
          this.setDataValue('password', security.hash(clearTextPassword))
        }
      },` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Syntax error Syntax error at line frontend/src/app/Services/user.service.ts:14:
 `new?:` was unexpected
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Timeout Timeout when running nodejs_scan.javascript-redirect-rule-express_open_redirect2 on frontend/src/assets/private/three.js:
 
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Timeout Timeout when running nodejs_scan.javascript-ssrf-rule-node_ssrf on frontend/src/assets/private/three.js:
 
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Timeout Timeout when running nodejs_scan.javascript-traversal-rule-express_lfr on frontend/src/assets/private/three.js:
 
[WARN] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/sarif/sarif.go:434] ▶ tool notification warning: Timeout Timeout when running nodejs_scan.javascript-dos-rule-regex_dos on server.ts:
 
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/gitlab/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/lgpl/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/lgpl-cc/LICENSE
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/src/buildapp/rules/ruleinfo.go:307] ▶ skipping parse for non-rule file: /rules/manifest.json
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/report.go:214] ▶ No Ids found to disable
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/report.go:256] ▶ Applying report overrides
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/report/v5@v5.7.0/report.go:275] ▶ No Ids found to override
[DEBU] [Semgrep] [2025-03-29T06:04:23Z] [/go/pkg/mod/gitlab.com/gitlab-org/security-products/analyzers/command/v3@v3.1.0/jsonout.go:54] ▶ Optimizing JSON Output
Uploading artifacts for successful job
00:02
Uploading artifacts...
gl-sast-report.json: found 1 matching artifact files and directories 
Uploading artifacts as "sast" to coordinator... 201 Created  id=9563812649 responseStatus=201 Created token=66_qQzkXk
Cleaning up project directory and file based variables
00:00
Job succeeded
